allow git repo specification for MythTV
in addition to allowing specification
of other (including local) repos, this
results in only one download per
invokation

diff --git a/MythTV/rpm/BUILD_MYTHWEB_RPMS b/MythTV/rpm/BUILD_MYTHWEB_RPMS
--- a/MythTV/rpm/BUILD_MYTHWEB_RPMS
+++ b/MythTV/rpm/BUILD_MYTHWEB_RPMS
@@ -4,6 +4,7 @@
 # Support mock config specification
 #
 MOCKOPTS=""
+REPO="https://github.com/MythTV/mythweb.git"
 while :; do
     case $1 in
         -r|--root)       # Takes an option argument; ensure it has been specified.
@@ -42,6 +43,18 @@ while :; do
         --without=*)
             MOCKOPTS="$MOCKOPTS $1"
             ;;
+        --repo)
+            if [ ! -z "$2" ]; then
+                REPO="$2"
+                shift
+            else
+                printf 'ERROR: "--repo" requires a non-empty option argument.\n'
+                exit 1
+            fi
+            ;;
+        --repo=*)
+            REPO="${1#*=}"
+            ;;
         --)              # End of all options.
             shift
             break
@@ -71,7 +84,7 @@ fi
 #
 TMPCLONEDIR=`mktemp -d`
 pushd $TMPCLONEDIR >/dev/null
-git clone https://github.com/MythTV/mythweb.git mythweb
+git clone $REPO mythweb
 pushd mythweb >/dev/null
 git checkout $GITCOMMITISH
 if [ $? -ne 0 ]; then
@@ -95,10 +108,6 @@ fi
 RPMVERSION=${GITDESCRIBE:1}
 RPMVERSION=${RPMVERSION//-/.}
 
-# Cleanup our clones
-rm -rf $TMPCLONEDIR/mythweb
-rmdir $TMPCLONEDIR
-
 #
 # Announce to world and dog what we are doing
 #
@@ -117,12 +126,15 @@ cp -r SPECS $TMPSDIR/
 sed -i -e "s/^Version: .*/Version:        $RPMVERSION/" $TMPSDIR/SPECS/mythweb.spec
 sed -i -e "s/^%global commit .*/%global commit $GITCOMMIT/" $TMPSDIR/SPECS/mythweb.spec
 
-# Use spectool to get source
-spectool --get-files --force --source=0 --directory=$TMPSDIR/SOURCES $TMPSDIR/SPECS/mythweb.spec
-if [ $? -ne 0 ]; then
-    echo "Unable to retrieve source files via spectool"
-    exit 1
-fi
+# Use git-archive to create source tarball from our clone
+pushd $TMPCLONEDIR/mythweb > /dev/null
+git archive --output $TMPSDIR/SOURCES/mythweb-$GITCOMMIT.tar.gz --prefix mythweb-$GITCOMMIT/ $GITCOMMIT
+popd >/dev/null
+
+# Cleanup our clone
+rm -rf $TMPCLONEDIR/mythweb
+rmdir $TMPCLONEDIR
+
 
 #
 # Build buildable src.rpm
