revise script for cleaner building of DEBS for hdhomerun_record

diff --git a/hdhomerun-record/deb/BUILD_DEBS b/hdhomerun-record/deb/BUILD_DEBS
--- a/hdhomerun-record/deb/BUILD_DEBS
+++ b/hdhomerun-record/deb/BUILD_DEBS
@@ -1,4 +1,4 @@
-#!/bin/bash -x
+#!/bin/bash
 
 HDHRDVR_VERSION=$1
 
@@ -9,25 +9,45 @@ fi
 
 export HDHRDVR_VERSION
 
-ARCH=`arch`
-
-CFGARCH=$ARCH
-if [ "$CFGARCH" == "armv7l" ]; then
-    CFGARCH='armhf'
-fi
+BUILDFAILURE=0
 
 BUILDDIR=`mktemp -d`
-
-echo $BUILDDIR
 
 mkdir -p $BUILDDIR/hdhomerun-record
 
 cp -R debian $BUILDDIR/hdhomerun-record
 
+pushd $BUILDDIR/hdhomerun-record >/dev/null
+
 for TARGET_ARCH in "i386" "amd64" "armhf" "arm64"
 do
-  echo "Target arch is " $TARGET_ARCH
-  ( cd $BUILDDIR/hdhomerun-record ; dpkg-buildpackage -b -d -us -uc --host-arch=$TARGET_ARCH )
+  dpkg-buildpackage -b -d -us -uc --host-arch=$TARGET_ARCH
+    if [ ! $? -eq 0 ]; then
+      echo ""
+      echo "***********************************************************"
+      echo "******** Build failed, logs in $BUILDDIR ********"
+      echo "***********************************************************"
+      echo ""
+      BUILDFAILURE=1
+    fi
 done
 
+popd >/dev/null
+
 cp $BUILDDIR/*.deb DEBS/
+
+if [ $BUILDFAILURE -eq 1 ]; then
+    echo ""
+    echo "***********************************************************"
+    echo "********** One or more builds failed, check logs **********"
+    echo "***********************************************************"
+    echo ""
+    exit 1
+fi
+
+# Clean up after ourselves
+rm -f $BUILDDIR/*.deb
+rm -f $BUILDDIR/*.buildinfo
+rm -f $BUILDDIR/*.changes
+rm -fr $BUILDDIR/hdhomerun-record
+rmdir $BUILDDIR
